"""
Tool admin per generare versioni offuscate di segreti.

Esegui questo OFFLINE e copia l'output nel codice sorgente.
NON committare l'output su repository pubblici!

Usage:
    python admin/tools/generate_obfuscated_keys.py

Author: Migration Team
Version: 1.0.0 (Nuitka Migration - Security Hardening)
"""
import sys
import os

# Fix Windows console encoding for emoji support
if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

# Ensure project root is in path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from app.core.string_obfuscation import obfuscate_string, deobfuscate_string, _XOR_KEY


def main():
    print("\n" + "=" * 70)
    print("🔐 KEY OBFUSCATOR - Intelleo Security Tool")
    print("=" * 70)
    print("Questo tool genera versioni offuscate di stringhe sensibili.")
    print("⚠️  NON committare l'output su repository pubblici!")
    print(f"XOR Key: 0x{_XOR_KEY:02X} ({_XOR_KEY})")
    print("=" * 70 + "\n")
    
    # Chiavi predefinite da offuscare
    secrets = {
        "FERNET_KEY": "8kHs_rmwqaRUk1AQLGX65g4AEkWUDapWVsMFUQpN9Ek=",
    }
    
    # Input opzionali
    print("📝 Input opzionali (premi ENTER per saltare):\n")
    
    google_key = input("   Google API Key: ").strip()
    if google_key:
        secrets["GOOGLE_API_KEY"] = google_key
    
    github_token = input("   GitHub Token: ").strip()
    if github_token:
        secrets["GITHUB_TOKEN"] = github_token
    
    custom_secret = input("   Custom Secret (nome:valore): ").strip()
    if custom_secret and ":" in custom_secret:
        name, value = custom_secret.split(":", 1)
        secrets[name.strip().upper()] = value.strip()
    
    # Genera output
    print("\n" + "=" * 70)
    print("📋 COPY-PASTE NEL CODICE SORGENTE:")
    print("=" * 70)
    
    print("\n# --- Obfuscated Secrets ---")
    print("# Generated by admin/tools/generate_obfuscated_keys.py")
    print(f"# XOR Key: 0x{_XOR_KEY:02X}")
    print("from app.core.string_obfuscation import deobfuscate_string\n")
    
    for name, secret in secrets.items():
        obfuscated = obfuscate_string(secret)
        
        # Verifica roundtrip
        recovered = deobfuscate_string(obfuscated)
        if recovered != secret:
            print(f"# ⚠️ WARNING: Roundtrip failed for {name}!")
            continue
        
        print(f"# {name}")
        print(f'_{name}_OBFUSCATED = "{obfuscated}"')
        print(f"def get_{name.lower()}() -> str:")
        print(f'    """Retrieves {name} at runtime (deobfuscated)."""')
        print(f"    return deobfuscate_string(_{name}_OBFUSCATED)")
        print()
    
    print("=" * 70)
    print("✅ Copia le righe sopra nei tuoi moduli Python")
    print("=" * 70)
    
    # Mostra anche formato per bytes (Fernet key)
    print("\n📝 FORMATO ALTERNATIVO PER BYTES (Fernet):")
    print("-" * 70)
    fernet_obf = obfuscate_string(secrets["FERNET_KEY"])
    print(f"""
# In app/core/license_security.py:
from app.core.string_obfuscation import deobfuscate_string

_FERNET_KEY_OBFUSCATED = "{fernet_obf}"

def get_license_secret_key() -> bytes:
    \"\"\"Retrieves the license secret key (deobfuscated at runtime).\"\"\"
    return deobfuscate_string(_FERNET_KEY_OBFUSCATED).encode('ascii')
""")
    print("-" * 70)


if __name__ == "__main__":
    main()

