"""
License Security Module - Secure key management for license encryption.

This module provides secure access to the Fernet encryption key used for
license file (config.dat) encryption/decryption.

Security Layers:
1. Static obfuscation: Key is XOR + Base64 encoded (not visible via `strings`)
2. Runtime protection: Key is decoded only when needed
3. Memory safety: Decoded key should be used immediately and discarded

Author: Migration Team
Version: 2.0.0 (Nuitka Migration - Security Hardening)
"""

import os

from app.core.string_obfuscation import deobfuscate_string

# =============================================================================
# OBFUSCATED SECRETS
# =============================================================================
# Generated by: python admin/tools/generate_obfuscated_keys.py
# XOR Key: 0x7B (123)
#
# SECURITY NOTE: This obfuscation prevents simple `strings` extraction.
# It is NOT cryptographically secure - for high-security scenarios,
# consider HSM or external key management.
# =============================================================================

# Fernet key for license encryption (obfuscated)
_FERNET_KEY_OBFUSCATED = "QxAzCCQJFgwKGikuEEo6Kjc8I01OHE86PhAsLj8aCywtCDY9LioLNUI+EEY="


class SecureKey:
    """
    Protects sensitive keys in memory using runtime XOR obfuscation.

    The key is stored encrypted with a random nonce and only decrypted
    transiently when accessed. This provides defense against memory dumps.
    """

    def __init__(self, key_bytes: bytes):
        # Generate a random nonce for runtime memory protection
        self._nonce = os.urandom(len(key_bytes))
        # Store key XOR nonce (not plaintext in memory)
        self._blob = bytes(a ^ b for a, b in zip(key_bytes, self._nonce, strict=False))

    @property
    def value(self) -> bytes:
        """
        Returns the decrypted key.

        Decryption happens on-the-fly each time.
        Callers should use the value immediately and let it go out of scope.
        """
        return bytes(a ^ b for a, b in zip(self._blob, self._nonce, strict=False))


def _initialize_secure_store() -> SecureKey:
    """
    Initializes the secure key store by deobfuscating the static key.

    This function is called once at module load time. The deobfuscated
    key is immediately wrapped in SecureKey for runtime memory protection.
    """
    # Deobfuscate the static key (XOR + Base64 decode)
    plaintext_key = deobfuscate_string(_FERNET_KEY_OBFUSCATED)
    key_bytes = plaintext_key.encode("ascii")

    # Wrap in SecureKey for runtime protection
    return SecureKey(key_bytes)


# Initialize the secure storage at module load
# The literal key is deobfuscated once and then protected in memory
_SECURE_STORE = _initialize_secure_store()


def get_license_secret_key() -> bytes:
    """
    Retrieves the license secret key for Fernet encryption/decryption.

    Security Notes:
    - The key is deobfuscated from static storage at module load
    - Runtime protection via XOR with random nonce
    - Callers should use the key immediately and let it go out of scope
    - Do NOT cache this value in long-lived variables

    Returns:
        bytes: The Fernet encryption key (44 bytes, Base64-encoded)

    Example:
        from cryptography.fernet import Fernet
        key = get_license_secret_key()
        cipher = Fernet(key)
        # Use cipher immediately...
        del key  # Clear from local scope
    """
    return _SECURE_STORE.value
